version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-urlfrontier:
    container_name: whirlpool-urlfrontier
    entrypoint: java -cp whirlpool-urlfrontier-1.0-SNAPSHOT-jar-with-dependencies.jar crawler.whirlpool.urlfrontier.Main
    environment:
      - MAVEN_CONFIG=/var/maven/.m2
      - JAVA_ENV=development

    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
